CHANGELOG.md
client/package-lock.json
client/package.json
package-lock.json
package.json

* Populated `CHANGELOG.md`
* Changed version number to reflect initial release
Vsix release: 
[openfga-vscode-0.1.0.vsix.zip](https://github.com/openfga/vscode-ext/files/12242920/openfga-vscode-0.1.0.vsix.zip)

chore: populate CHANGELOG.md

---

.github/workflows/publish.yaml
CHANGELOG.md

* Set up dryRun for publishing in github workflow for publishing to marketplace
* `CHANGELOG` internal release --> initial release
- Closes https://github.com/openfga/vscode-ext/issues/6

chore: Prepare for publish

---

.vscode/launch.json
client/src/extension.ts
package.json
server/package-lock.json
server/package.json
server/src/server.ts
server/tsconfig.json
tsconfig.json
webpack.config.js

Coupled the example language server back up, and added a validation check
Addresses https://github.com/openfga/language/issues/17 but still more refinement can be done.
[openfga-vscode-0.1.0.vsix.zip](https://github.com/openfga/vscode-ext/files/12261805/openfga-vscode-0.1.0.vsix.zip)

feat: Language server with validation

---

.github/workflows/upload-artifact.yaml

Create a workflow to generate and publish the latest code as a VSIX file.
https://github.com/openfga/vscode-ext/issues/47
https://github.com/openfga/vscode-ext/actions/runs/5766362585?pr=52

chore: create VSIX in github workflow

---

README.md

chore(docs): add OpenVSX registry link to readme

---

CHANGELOG.md
package-lock.json
package.json

[openfga-vscode-0.2.0.vsix.zip](https://github.com/openfga/vscode-ext/files/12693238/openfga-vscode-0.2.0.vsix.zip)

chore: version bump 0.2.0

---

snippets.json

fix: schema snippet

---

README.md

chore: Update README with structure and testing changes

---

CHANGELOG.md
package-lock.json
package.json

release: v0.2.1

---

.gitignore
README.md
docs/DEVELOPMENT.md

chore: mode developer docs to a different page

---

CHANGELOG.md
package-lock.json
package.json

Added setting to enable debug logs

release: v0.2.2

---

CHANGELOG.md
package-lock.json
package.json

release: v0.2.3

---

server/src/code-action.ts
server/src/server.common.ts

* Enabled code actions
* Ported over some actions from `syntax-transformer`
// TODO: Testing

feat: code action

---

CHANGELOG.md
client/package-lock.json
client/package.json
package-lock.json
package.json
server/package-lock.json
server/package.json

* version-bumped `syntax-transformer`
* added to CHANGELOG
* bumped release number

release: v0.2.4

---

server/src/server.common.ts

* Added validation to `model` field in YAML files
https://github.com/openfga/vscode-ext/assets/1425457/09a07637-1608-439b-a7d7-a1a3a641dff1

feat: DSL validation in YAML

---

package-lock.json
package.json

* Added `npm run build:vsix` command
* Added `vsce` as dev dependency

chore: Adding vsix build script

---

syntaxes/injection.json

* Simplified matching for model tag.

fix: model keyword not showing as comment

---

CHANGELOG.md
package-lock.json
package.json

* Version bump
* CHANGELOG update
* Syntax and validation support for embedded OpenFGA models

release: v0.2.5

---

.github/workflows/dryrun-publish.yaml
.github/workflows/main.yaml
.github/workflows/publish.yaml

* Making main.yaml reusable for publishing workflow

chore: adding test to publish workflow

---

.github/workflows/publish.yaml
.github/workflows/upload-artifact.yaml

* Added create release steps for both publish and dryrun
* Reused `upload-artifact.yaml`
Actions used 
* https://github.com/Roang-zero1/github-create-release-action
* https://github.com/svenstaro/upload-release-action

chore: create release and attach vsix

---

server/src/server.common.ts

When the language is changed for a document, diagnostics will continue to persist. If the language is changed for an untitled file, the "didClose" event is fired for the document. If we received that the doc is closed, we can clear the diagnostics.

fix: Clear diagnostics on doc close

---

server/src/openfga-yaml-schema.ts
server/src/server.common.ts
syntaxes/openfga.injection.json

* Allow spaces after `model` and trailing spaces after the `|`
* Added required fields
* Improved diagnostic location for array items

fix: yaml validation

---

CHANGELOG.md
package-lock.json
package.json

[openfga-latest.vsix.zip](https://github.com/openfga/vscode-ext/files/13231566/openfga-latest.vsix.zip)

release: 0.2.7

---

CHANGELOG.md
package-lock.json
package.json
server/src/openfga-yaml-schema.ts
server/src/server.common.ts

- Addressed issues with enforced fields in yaml
- Disabled unimplemented completion
- Removed debug messages

fix: disable completion & relax required yaml fields

---

.gitignore
client/package-lock.json
client/package.json
client/src/extension.browser.ts
client/src/extension.node.ts
client/src/test/extension.test.ts
server/package-lock.json
server/package.json

fix: bump syntax transformer to better support conditions

---

server/src/openfga-yaml-schema.ts

fix: store file schema

---

CHANGELOG.md
client/package-lock.json
client/package.json
package-lock.json
package.json
server/package-lock.json
server/package.json

release(v0.2.9): with conditions support and fixes to store yaml schema

---

package.json
syntaxes/cel.injection.json

* CEL being correctly embedded in the FGA, in YAML.

fix: Inject CEL into YAML source

---

CHANGELOG.md
package-lock.json
package.json

release: v0.2.10

---

CHANGELOG.md
package-lock.json
package.json

Release for Initial limited support for mixing operators

release(v0.2.11): Initial limited support for mixing operators

---

CHANGELOG.md
client/package-lock.json
client/package.json
package-lock.json
package.json
server/package-lock.json
server/package.json
server/src/server.common.ts

release(v0.2.12): with a crash fix when validating some valid models

---

.github/workflows/main.yaml

chore: allow continue on audit error

---

package-lock.json
server/package-lock.json
server/package.json
server/src/helpers.ts
server/src/openfga-yaml-schema.ts
server/src/server.common.ts

Most recent build
[openfga-latest.vsix.zip](https://github.com/openfga/vscode-ext/files/13734197/openfga-latest.vsix.zip)

feat: Store field validation

---

CHANGELOG.md
package-lock.json
package.json

release(v0.2.13): Validation for YAML stores

---

server/src/openfga-yaml-schema.ts
server/src/server.common.ts

* Added tuple validation to `test tuples`
* Added validation for assertions and context of Check & ListObjects 
* Added warning and stopped validating when 1000 tuples are reached
* Added warning to user fields in checks to warn when a tuple is declared with an undefined user

feat: test tuple validation

---

CHANGELOG.md
package-lock.json
package.json

release(0.2.14): Test tuple Validation

---

server/src/openfga-yaml-schema.ts

* Correct linting errors
* Add warning about objects

feat: object validation

---

CHANGELOG.md
package-lock.json
package.json

* Added warnings when a declared check object value doesnt exist in the tuples

release(0.1.15): check object warnings

---

syntaxes/openfga.tmLanguage.json
themes/openfga-dark.json

- fixes https://github.com/openfga/vscode-ext/issues/122
- fixes https://github.com/openfga/vscode-ext/issues/125
- fixes https://github.com/openfga/vscode-ext/issues/141

fix: textmate grammar

---

CHANGELOG.md
package-lock.json
package.json

release(v0.2.16): syntax issues

---

.github/dependabot.yaml
client/package-lock.json
client/package.json
package-lock.json
server/package-lock.json
server/package.json

chore: update dependencies

---

CHANGELOG.md
package-lock.json
package.json

release(v0.2.18): support for model_file, and tuple_file

---

server/package-lock.json
server/package.json
server/src/dsl-utils.ts

* Bump to `syntax-transformer` to 0.2.0-beta.11
* Removed `getLine` and `getCol`

chore: version bump to syntax-transformer

---

CHANGELOG.md
package-lock.json
package.json

release(v0.2.19): fix  user & object formatter to allow '/' in ids

---

package.json

- resolves https://github.com/openfga/vscode-ext/issues/166

feat: register fga.mod as OpenFGA Module file

---

client/src/extension.browser.ts
client/src/extension.node.ts
package.json
syntaxes/openfga.tmLanguage.json
themes/openfga-dark.json

- resolves https://github.com/openfga/vscode-ext/issues/167

feat: syntax highlighting for `fga.mod` files

---

server/package-lock.json
server/package.json
server/src/server.common.ts

Expected to fail due to reference to local path for `@openfa/language`
- resolves https://github.com/openfga/vscode-ext/issues/169

feat: transformation and validation

---

CHANGELOG.md
client/package-lock.json
client/package.json
client/src/extension.node.ts
package-lock.json
package.json
server/package-lock.json
server/package.json
server/src/dsl-utils.ts
server/src/server.common.ts
server/src/yaml-utils.ts
webpack.config.js

- closes https://github.com/openfga/vscode-ext/issues/170
[openfga-latest.vsix.zip](https://github.com/openfga/vscode-ext/files/14672227/openfga-latest.vsix.zip)
More work is needed to validate a modular model, which will be completed with https://github.com/openfga/vscode-ext/issues/171

feat: initial beta support for Modular Models

---

client/package-lock.json
client/package.json
server/package-lock.json
server/package.json
server/src/client-utils.ts
server/src/dsl-utils.ts
server/src/server.common.ts
server/src/yaml-utils.ts

- closes https://github.com/openfga/vscode-ext/issues/171

feat: Validation for individual modular model files

---

client/package-lock.json
client/package.json
server/package-lock.json
server/package.json
server/src/dsl-utils.ts
server/src/server.common.ts

* `store.fga.yaml` support for modular models
* Replace multitude of error instanceof checks with an abstract 
This PR's success relies on https://github.com/openfga/language/commit/18b0254b2be1766f709cf4148cf46dcc2cb53407
- closes https://github.com/openfga/vscode-ext/issues/172

feat: store can point to a fga.mod file

---

server/src/openfga-yaml-schema.ts

* Add `|` to allowed character list for object id

fix: allow pipe in object id

---

client/package-lock.json
client/package.json
server/package-lock.json
server/package.json
server/src/dsl-utils.ts
server/src/server.common.ts

Tests will pass once the latest https://github.com/openfga/language version is released

fix: the range for language exceptions

---

CHANGELOG.md
package-lock.json
package.json

- closes https://github.com/openfga/vscode-ext/issues/165
[openfga-latest.vsix.zip](https://github.com/openfga/vscode-ext/files/14877874/openfga-latest.vsix.zip)

release: v0.2.21

---

server/src/openfga-yaml-schema.ts

fix: Adding @ to allowable characters in id

---

README.md

Fixes a broken link in the README to the development roadmap on GitHub
Fixes a broken link in the README to the development roadmap on GitHub:
https://github.com/orgs/openfga/projects/1
N/A

docs: fix roadmap link

---

syntaxes/openfga.injection.json

- fixes https://github.com/openfga/vscode-ext/issues/227
[openfga-latest.vsix.zip](https://github.com/openfga/vscode-ext/files/15097075/openfga-latest.vsix.zip)

fix: add block chomping for yaml store model field

---

CHANGELOG.md
package-lock.json
package.json

[openfga-latest.vsix.zip](https://github.com/openfga/vscode-ext/files/15241680/openfga-latest.vsix.zip)

release: v0.2.22

---

syntaxes/openfga.tmLanguage.json
themes/openfga-dark.json

[openfga-latest-latest.vsix.zip](https://github.com/user-attachments/files/15931285/openfga-latest-latest.vsix.zip)
- fixes https://github.com/openfga/intellij-plugin/issues/27

fix: syntax for custom themes

---

CHANGELOG.md
client/package-lock.json
client/package.json
package-lock.json
package.json
server/package-lock.json
server/package.json

v0.2.23 was manually pushed to VS Code marketplace and has an issue due to stale dependencies.
Closes #297

release: v0.2.24

---

.github/workflows/semgrep.yaml

We were using a deprecated version. This now mimics the one used by the rest of the SDKs, e.g. https://github.com/openfga/js-sdk/blob/main/.github/workflows/semgrep.yaml
If you haven't done so yet, we would appreciate it if you could star the [OpenFGA repository](https://github.com/openfga/openfga). :)

chore(ci): update semgrep action

---

README.md

Replaced License badge with OpenSSF Scorecard badge in README.

chore(docs): Update badges in README.md
