openfga/vscode-ext

.github/workflows/dryrun-publish.yaml

* Splitting dryrun and real release workflows
* Dryrun only manually invoked now via `workflow_dispatch`

chore: Seperate dryrun and real publish workflows

---

.github/workflows/main.yaml
README.md
client/src/test/extension.test.ts

* Was using the wrong `activate()` for tests. Changed to use correct helper method. 
- Closes https://github.com/openfga/vscode-ext/issues/15

fix(ci): Using correct activate for test suite

---

language-configuration.json
package.json
snippets.json

* Removed code that was not being used by language-configuration
* Added onEnter rules for text based indentation
* Tested manually for what felt expected when writting
Open to expanding further with more developer experience needed
- Closes https://github.com/openfga/vscode-ext/issues/21

fix: reduce to working language-configuration set

---

server/package-lock.json
server/package.json

Updated to latest @openfga/syntax-transformer beta, containing validation
Latest manual build:
[openfga-vscode-0.2.0.vsix.zip](https://github.com/openfga/vscode-ext/files/12692366/openfga-vscode-0.2.0.vsix.zip)

feat: update to latest syntax-transformer

---

package.json
server/src/server.common.ts

chore: add tracing

---

client/src/extension.browser.ts
client/src/extension.node.ts

Removed restriction on what schemes to support for OpenFGA document selector.
Tested on Dev Host, VSIX, and vscode.dev
Development Host:
VSIX install:
vscode.dev - saved model:
vscode.dev - untitled model:

fix: document selector not working in github.dev

---

.github/workflows/main.yaml
.vscode/launch.json
client/src/test/extension.test.ts
client/src/test/helper.ts
client/src/test/index.browser.ts
client/src/test/index.node.ts
package.json
scripts/e2e-node.sh

* Added env var `VSCODE_TEST_NODE` to dictate which file system structure to use whether in node or browser for the test suite. When set,`VSCODE_TEST_NODE` will use `file`, otherwise it uses `vscode-test-web` for browser.
* Changed github workflow to use `npm test` to run both node and web tests on a PR

fix: e2e tests working for node and web

---

.eslintrc.js
.galintignore
.github/workflows/main.yaml
.prettierrc
client/src/extension.browser.ts
client/src/extension.node.ts
client/src/test/diagnostics.test.ts
client/src/test/extension.test.ts
client/src/test/helper.ts
client/src/test/index.browser.ts
client/src/test/index.node.ts
client/src/test/runTest.ts
package-lock.json
package.json
server/src/server.browser.ts
server/src/server.common.ts
server/src/server.node.ts

* Copied configuration from syntax transformer
* Ignored lines complaining about missing `vscode` lib as it doesnt exist until run
* Left some warnings to revist

fix: Addressed all linting errors

---

client/package-lock.json
client/src/test/diagnostics.test.ts
client/src/test/hover.test.ts
server/package-lock.json
server/package.json
server/src/documentation.ts
server/src/server.common.ts
webpack.config.js

feat: hover info

---

syntaxes/cel.injection.json
syntaxes/openfga.tmLanguage.json

Highlighting CEL as [per this textMate grammar](https://github.com/hmarr/vscode-cel/blob/main/syntaxes/cel.tmLanguage.json)
This current grammar expects there only a single set of `{ }` parens for the condition expression.

fix: Lifting conditions grammar up to openfga

---

server/src/openfga-yaml-schema.ts

Simplify formatter to allow for `ids` as unstructured strings.
- fixes https://github.com/openfga/vscode-ext/issues/182

fix: user & object formatter to allow '/' in ids

---

server/package-lock.json
server/package.json
server/src/openfga-yaml-schema.ts

Support for https://github.com/openfga/cli/issues/304
Closes #204 
[openfga-latest.vsix.zip](https://github.com/openfga/vscode-ext/files/15242007/openfga-latest.vsix.zip)

feat: list_users support

---

server/src/openfga-yaml-schema.ts

- fixes https://github.com/openfga/vscode-ext/issues/257

fix: remove excluded user field from list_users

---

.github/dependabot.yaml

eslint 9.x.x has breaking changes and incompatibilities with a lot of the ecosystem plugins
https://github.com/openfga/vscode-ext/pull/277

chore: exclude eslint from dependabot updates

---

.vscode/launch.json
webpack.config.js

Small fix for webpack to enable the ability to debug with sourcemaps.

fix: webpack sourcemap generation

---

docs/DEVELOPMENT.md
docs/RELEASING.md

chore: update docs

---

.github/workflows/publish.yaml

Potential fix for [https://github.com/openfga/vscode-ext/security/code-scanning/3](https://github.com/openfga/vscode-ext/security/code-scanning/3)
To fix the problem, add an explicit `permissions` block to the `test` job in `.github/workflows/publish.yaml`. Since the job is named `test` and is likely only running tests (and not performing any write operations), the minimal required permissions are likely `contents: read`. This should be added directly under the `test:` job definition (i.e., at the same level as `uses:`). No other changes are needed, and this will not affect the existing functionality of the workflow.
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._

Potential fix for code scanning alert no. 3: Workflow does not contain permissions

---

.github/workflows/dryrun-publish.yaml

Potential fix for [https://github.com/openfga/vscode-ext/security/code-scanning/4](https://github.com/openfga/vscode-ext/security/code-scanning/4)
To fix the problem, we should add a `permissions` block to the workflow to explicitly restrict the permissions granted to the GITHUB_TOKEN. The best way to do this is to add the block at the root level of the workflow file, so it applies to all jobs that do not have their own `permissions` block. Based on the workflow's steps, the minimal required permission is likely `contents: read`, which allows jobs to read repository contents but not write to them. This change should be made at the top of the `.github/workflows/dryrun-publish.yaml` file, immediately after the `name:` field and before the `jobs:` field.
_Suggested fixes powered by Copilot …

Potential fix for code scanning alert no. 4: Workflow does not contain permissions

---

.github/workflows/publish.yaml

Potential fix for [https://github.com/openfga/vscode-ext/security/code-scanning/5](https://github.com/openfga/vscode-ext/security/code-scanning/5)
To fix the problem, we should add a `permissions` block to the `publish` job, specifying the minimal permissions required. Since the job appears to only need to read repository contents (for checkout and possibly for reading files), we should set `contents: read`. If, in the future, the job requires additional permissions (e.g., to create issues or pull requests), those can be added explicitly. The change should be made in `.github/workflows/publish.yaml`, by adding a `permissions` block under the `publish` job, above the `steps` key.
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._

Potential fix for code scanning alert no. 5: Workflow does not contain permissions

---

.github/workflows/dryrun-publish.yaml

Potential fix for [https://github.com/openfga/vscode-ext/security/code-scanning/2](https://github.com/openfga/vscode-ext/security/code-scanning/2)
To fix the problem, add a `permissions` block to the workflow file `.github/workflows/dryrun-publish.yaml`. This block should be placed at the top level (applies to all jobs unless overridden), and should specify the minimum required permissions. Since the workflow appears to only need to read repository contents (for checkout and install), and does not push code or create issues/pull requests, the minimal permission is likely `contents: read`. If any job requires more, it can be overridden at the job level. The change should be made by inserting the following block after the `name:` field and before `jobs:`.
---
_Suggested fixes powered by …

Potential fix for code scanning alert no. 2: Workflow does not contain permissions
